### ISSUE TITLE
git-seekret check not checking staged files or commits

### ISSUE THREAD

**Issue by alain-hoang** [apuigsech/git-seekret#22]
When running `git-seekret` on a repo with staged files with data that would match against a secret rules file, it is not detecting the secrets and reporting 0 secrets found.  When using the `seekret` command with the same ruleset it is reporting secrets found.

Example session below with abc.txt being the staged file in test repo:

```

$ git-seekret rules
List of rules:
	[x] aws.account_id
	[x] aws.secret_access_key
	[x] aws.access_key_id
	[x] newrelic.license_key

$ git-seekret  check --staged
Found Secrets: 0

$ seekret --rules /path/to/seekret-rules dir abc.txt           
abc.txt
	1: [aws.secret_access_key] aws_secret_access_key=1234567890123456789012345678901234567890 %!s(bool=false)
abc.txt
```

**Comment by apuigsech** [comment]
Good catch!
